#!/bin/sh
set -e
mkdir -p _build
if [[ ! -f _build/Converter.class ]] || [[ _build/Converter.class -ot src/Converter.java ]]; then
    printf "rebuilding... "
    javac -d _build src/Converter.java
    echo OK
fi
java -cp _build Converter $@
